play := GREEN + BOLD + "󰐊 "
hammer := GREEN + BOLD + "󰣪 "
check := GREEN + BOLD + "󰄬 "
flask := GREEN + BOLD + "󰂔 "

run *ARGS:
    @echo -e "{{play}}running project...{{normal}}"
    @cargo run {{ARGS}}

build:
    @echo -e "{{hammer}}building project...{{normal}}"
    @cargo build --release
    @echo -e "{{check}}successfully built to ./target/release/{{normal}}"

test:
    @echo -e "{{flask}}testing project...{{normal}}"
    @cargo test
    @echo -e "{{check}}tests passed{{normal}}"