play := GREEN + BOLD + "󰐊 "
hammer := GREEN + BOLD + "󰣪 "
check := GREEN + BOLD + "󰄬 "
flask := GREEN + BOLD + "󰂔 "

run *ARGS:
    @echo -e "{{play}}running project...{{NORMAL}}"
    @cargo run {{ARGS}}

build:
    @echo -e "{{hammer}}building project...{{NORMAL}}"
    @cargo build --release
    @echo -e "{{check}}successfully built to ./target/release/{{NORMAL}}"

test:
    @echo -e "{{flask}}testing project...{{NORMAL}}"
    @cargo test
    @echo -e "{{check}}tests passed{{NORMAL}}"