name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Test & Build
    steps:
      - uses: actions/checkout@v4
      - uses: extractions/setup-just@v3

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Build for all major platforms
        run: just build-all

      - name: Run tests
        run: just test

      - name: Run linter
        uses: golangci/golangci-lint-action@v8.0.0

      - name: Generate artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: build
