name: CI

on:
  push:
    paths:
      - "**.zig"
      - ".github/workflows/ci.yml"
  pull_request:
    paths:
      - "**.zig"
      - ".github/workflows/ci.yml"

jobs:
  build:
    runs-on: ubuntu-latest
    name: Check & Build
    steps:
      - uses: actions/checkout@v4
      - uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: zig-out
      - uses: extractions/setup-just@v3
      - uses: mlugg/setup-zig@v1.2.1

      - name: Code checks
        run: zig fmt --check --ast-check **.zig

      - name: Build all
        run: just build-all
